# Generated by Django 6.0.1 on 2026-01-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passsenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passsenger',
            new_name='Passenger',
        ),
    ]
